version: "3.9"
services:
  backend:
    build: ./backend
    networks:
      - bloodbank-network
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 5050:27017
      - 6000:27018
    networks:
      - bloodbank-network

  frontend:
    container_name: bloodbank-web
    image: nginx
    depends_on:
      - backend
    build: ./frontend
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/share/nginx/html
    links:
      - backend
    networks:
      - bloodbank-network

networks:
  bloodbank-network:
    driver: bridge
